version: '3.7'

services:
  keycloak:
    container_name: keycloak-user-admin-api
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_DB=postgres
      - KEYCLOAK_DB_URL=jdbc:postgresql://db:5432/keycloak
      - KEYCLOAK_DB_USERNAME=keycloak
      - KEYCLOAK_DB_PASSWORD=keycloak_password
      - KC_THEME=mytheme
      - MAILHOG_SMTP_HOST=mailhog:1025
      - MAILHOG_HTTP_HOST=mailhog:8025
    command: start-dev
    ports:
      - 8081:8080
    depends_on:
      - db
      - mailhog
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./keycloak-theme/themes:/opt/keycloak/themes

  db:
    container_name: keycloak-db
    image: postgres:13
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  keycloak_data:
    driver: local
  postgres_data:
    driver: local
